# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171214_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=123456, max_length=32, verbose_name='用户名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=123, max_length=32, verbose_name='用户名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(default=12, max_length=32, verbose_name='用户名称'),
            preserve_default=False,
        ),
    ]
